### ISSUE TITLE
question about the data collction tools

### ISSUE THREAD

**Issue by DarrenWong** [SIAT-INVS/CarlaFLCAV#3]
Thanks for sharing the great work! I have a question regarding the data collection tools following the [step](https://github.com/SIAT-INVS/CarlaFLCAV/tree/main/FLDatasetTool) 

I am able to run the 

`python3 data_recorder.py
`
The log and output 
![image](https://user-images.githubusercontent.com/5771106/203679539-ccb10c47-a442-4bb7-a5b4-849947d0e09e.png)

and 
![image](https://user-images.githubusercontent.com/5771106/203679446-20e34ddf-9e97-4c65-8f62-307159376663.png)

The NPC vehicles are normal, but the data collection vehicles crash after a few seconds.

My question is: Do I need to add some parameters to make it work? I am thinking of too many collection vehicle problems but still not working after one vehicle left. (tried running on Ubuntu 20.04 and 18.04)

1. Worldview 

![image](https://user-images.githubusercontent.com/5771106/203679878-1d0df9b7-7172-401f-a215-9e4020d550c0.png)

2. Vehicle camera view
![0000000010](https://user-images.githubusercontent.com/5771106/203680107-8170cf12-3178-4d27-a67f-ebf6a2a40902.png)

![0000000031](https://user-images.githubusercontent.com/5771106/203680159-a0cd1064-5ca7-4d86-bc8d-948684f11e44.png)

![0000000073](https://user-images.githubusercontent.com/5771106/203680168-040fc7ed-d53a-447f-8422-a3da8c266b0c.png)

Thanks a lot

**Comment by KevinLADLee** [comment]
Hi @DarrenWong , there is something unstable with  carla.agent module in some cases. 

You could enable the autopilot mode. Just change this flag to True. 
https://github.com/SIAT-INVS/CarlaFLCAV/blob/b07e6e6b956bc02055131758a6dda7e3a1fdf05a/FLDatasetTool/recorder/vehicle.py#L23

**Comment by DarrenWong** [comment]
Cool! It works. Also, it is very helpful to generate the KITTI labels for detection task!
